### ISSUE TITLE
我想只输入LR图片进行测试的话，具体该怎么做呢？

### ISSUE THREAD

**Issue by zyf1040895256** [LongguangWang/DASR#12]
如标题，在trainer.py里面没有看到有用到直接提供LR路径的地方，只有HR降质到LR再进行SR处理的过程，如果我想要直接输入LR图片进行输出该如何处理？
万分谢谢您的回复！

**Comment by LongguangWang** [comment]
@zyf1040895256 你好，感谢对我们工作的关注。我添加了一个用于直接对低分辨率图像进行测试的`quick_test.py`，请参考[readme](https://github.com/LongguangWang/DASR#quick-test-on-an-lr-image)进行使用。

**Comment by zyf1040895256** [comment]
> @zyf1040895256 你好，感谢对我们工作的关注。我添加了一个用于直接对低分辨率图像进行测试的`quick_test.py`，请参考[readme](https://github.com/LongguangWang/DASR#quick-test-on-an-lr-image)进行使用。

谢谢！
