### ISSUE TITLE
PSNR and SSIM

### ISSUE THREAD

**Issue by wangchust** [LongguangWang/DASR#14]
Hi, author. Thank you for your excellent work. But I'm a little confused about the code which calculate PSNR and SSIM metric.  For PSNR, why the diff is multipide by a convert coefficient and shave the border when benchmarch is set to True. For SSIM, why not directly use api from skimage? Waiting for your response, sincerely.

**Comment by LongguangWang** [comment]
Hi @wangchust, thanks for your interest in our work. We follow the settings widely used in existing SR methods (e.g., [RCAN](https://github.com/yulunzhang/RCAN/blob/master/RCAN_TestCode/code/utility.py#L151)) for performance evaluation. The convert coefficients are used to calculate the luminance channel and the borders are shaved for fair comparison. For SSIM, we modified the code from [BasicSR](https://github.com/xinntao/BasicSR/blob/cf1e32cdfc9710041ed497e9f5c155ceb7567c8f/basicsr/metrics/psnr_ssim.py#L84).

**Comment by wangchust** [comment]
I've got it. Thanks for yours explanation
