### ISSUE TITLE
非常感谢您在图像超分领域做出的工作，对我的研究非常有帮助。对于您论文中的Figure 3. 是由Model 1和Model 4得到，但是Model 1是没有Degradation Representation Learning ，那么Model 1的退化表示是怎么得到的呢？您能够提供一下您可视化的代码么？我使用T-sne进行可视化，完全区分不开两者。

### ISSUE THREAD

**Issue by fxlong** [LongguangWang/DASR#19]

**Comment by fxlong** [comment]
非常感谢您在图像超分领域做出的工作，对我的研究非常有帮助。对于您论文中的Figure 3. 是由Model 1和Model 4得到，但是Model 1是没有Degradation Representation Learning ，那么Model 1的退化表示是怎么得到的呢？您能够提供一下您可视化的代码么？我使用T-sne进行可视化，完全区分不开两者。

**Comment by LongguangWang** [comment]
Hi @fxlong, 感谢对我们工作的关注。
model 1的网络结构与model 4完全一致，仍然保留了degradation encoder，只是去掉了contrastive loss。可视化代码请参考[这里](https://drive.google.com/file/d/1PF7NSob4-M2UWXHYCu2kdr23R703z2F0/view)。
