### ISSUE TITLE
关于论文中Figure 6. 的绘制

### ISSUE THREAD

**Issue by fxlong** [LongguangWang/DASR#20]
感谢您在图像超分领域的贡献，您的工作对我有很大的帮助。请问下图6中用于提取degradation representations的moco是怎么训练的？是正常的训练还是只用了4种模糊核的数据进行训练？能提供下该部分的代码吗？

**Comment by LongguangWang** [comment]
你好，图6中绘图使用的模型就是正常训练得到的模型，而不是只是用了图中的4种模糊核进行训练的。训练代码请参考[这里](https://github.com/LongguangWang/DASR#train)。
