### ISSUE TITLE
blur kernels in Tab.3

### ISSUE THREAD

**Issue by sujyQ** [LongguangWang/DASR#25]
Hi. I'm sorry to bothering you.
Does this paper contain information about eigen values and rotate angles of the blur kernels in Tab.3 ?
I can see just shapes.

**Comment by LongguangWang** [comment]
Hi @sujyQ, thanks for your interest in our work.
The detailed settings of the blur kernels in Tab. 3 are shown below.
![image](https://user-images.githubusercontent.com/37017318/127590001-372d1635-0e62-4126-9963-bbc196dba526.png)
While re-producing the results in Tab. 3, we find a [bug](https://github.com/LongguangWang/DASR/blob/main/utils/util.py#L54) and fix it. We also notice that a wrong pre-trained model for anisotropic kernels is released by mistake and we have uploaded the correct one.

**Comment by sujyQ** [comment]
Thanks :)

**Comment by Lewis0427** [comment]
util代码中random_anisotropic_gaussian_kernel里面您的更改是否有错误：theta = torch.rand(batch).cuda() / 180 * math.pi
是否应是theta = torch.rand(batch).cuda() * math.pi，180无需再加了

**Comment by LongguangWang** [comment]
@Lewis0427，感谢指出这一bug，我们已经对其进行了修复。
