### ISSUE TITLE
单GPU训练该如何修改代码呢？我应该如何设置单GPU训练？

### ISSUE THREAD

**Issue by lct1997** [LongguangWang/DASR#29]
感谢您的工作。我在训练过程中，由于只有单GPU，所以在数据并行的部分出现了报错
通过查阅相关资料，这个问题仍没有解决，所以想向您咨询一下该如何处理这个问题
![1](https://user-images.githubusercontent.com/63594482/128284118-450c8149-f13e-4993-b3c7-a233b24859f5.png)
![2](https://user-images.githubusercontent.com/63594482/128284123-c7e1471d-cdbc-459e-994d-a8834fd23704.png)

**Comment by LongguangWang** [comment]
Hi @lct1997, 请问有没有将[这里](https://github.com/LongguangWang/DASR/blob/main/option.py#L16)的n_GPUs设置为1。

**Comment by lct1997** [comment]
抱歉这么晚还打扰您。您指出的部分我已设置为1，但仍然报上面的错误。我也测试过其他的代码，GPU是正常使用的，所以才冒昧打扰您，希望给出解决办法，谢谢您！

**Comment by LongguangWang** [comment]
你好，在我这边设置n_GPUs为1后可以正常使用1个卡运行。能提供完整的报错信息么？

**Comment by lct1997** [comment]
您好，我这边重新下载您更新过后的代码，按您说的方法修改就可以用运行了。我之前运行的是您几个月前的代码了，所以存在bug，很抱歉耽误您的时间，谢谢您耐心答疑！

**Comment by LongguangWang** [comment]
好的，抱歉因为之前的bug带来不便。
