### ISSUE TITLE
psnr results

### ISSUE THREAD

**Issue by sujyQ** [LongguangWang/DASR#30]
Hi. I'm sorry to bothering you.

Are the PSNR results calculated by MATLAB with YCbCr space or by your calc_psnr in utility.py?

Thanks!

**Comment by LongguangWang** [comment]
Hi @sujyQ, thanks for your interest in our work. In our experiments, we calculate PSNR values using cal_psnr function ([here](https://github.com/LongguangWang/DASR/blob/main/trainer.py#L167)). You can also use Matlab to calculate them and the results will be the same.

**Comment by sujyQ** [comment]
I've got it! THX:)
