### ISSUE TITLE
the latest torch version

### ISSUE THREAD

**Issue by sujyQ** [LongguangWang/DASR#31]
Hi. I'm sorry to bothering you.

How can i change the code for the latest torch version?

For torch==1.7.1 I think _DataLoaderIter matters.

**Comment by LongguangWang** [comment]
Hi @sujyQ, you can refer to [this answer](https://github.com/HolmesShuan/OISR-PyTorch/issues/6#issuecomment-615517353) and revise the dataloader in EDSR (pytorch 1.2.0). Usually, directly copying the code of [_DataLoaderIter](https://github.com/pytorch/pytorch/blob/v1.1.0/torch/utils/data/dataloader.py#L199) to torch.utils.data.dataloader.py may also solve this issue.

**Comment by wwlCape** [comment]
@sujyQ Has your problem been solved? I am using the same higher version of PyTorch, and the code will report an error.

**Comment by sujyQ** [comment]
Hi @wwlCape

I made a file data/loader.py and then copied [this](https://github.com/pytorch/pytorch/blob/0b868b19063645afed59d6d49aff1e43d1665b88/torch/utils/data/dataloader.py) and pasted to the data/loader.py.

**Comment by jjlinghu** [comment]
> @sujyQ Thank you for your replying. I try to deal with the problem with your method, but raise up another error"TypeError: cannot unpack non-iterable NoneType object". Could you please send a copy of your /data filefolder and dataloader.py file to my email? ([wenwlmail@163.com](mailto:wenwlmail@163.com))Thank you very much.

you can copy the copy the code of [_DataLoaderIter](https://github.com/pytorch/pytorch/blob/v1.1.0/torch/utils/data/dataloader.py#L199) to torch.utils.data.dataloader.py
