### ISSUE TITLE
How can I solve this problem?

### ISSUE THREAD

**Issue by raychl94** [LongguangWang/DASR#88]
您好，我遇到以下问题，烦请有空时帮忙解决解决一下。
报错内容：
Traceback (most recent call last):
  File "E:/DASR-main/main.py", line 19, in <module>
    t.train()
  File "E:\DASR-main\trainer.py", line 63, in train
    for batch, (hr, _, idx_scale) in enumerate(self.loader_train):
ValueError: not enough values to unpack (expected 3, got 2)

option.py 中的对应设置
# Hardware specifications
parser.add_argument('--n_threads', type=int, default=0,
                    help='number of threads for data loading')
parser.add_argument('--cpu', type=bool, default=False,
                    help='use cpu only')
parser.add_argument('--n_GPUs', type=int, default=1,
                    help='number of GPUs')
parser.add_argument('--seed', type=int, default=1,
                    help='random seed')

当我把-n_threads设置成1时就第一个epoch就卡住不动，我该如何解决这个问题？谢谢

**Comment by LongguangWang** [comment]
您好，请问LR和HR数据是怎么存放的，同时还修改了哪些地方么？

**Comment by raychl94** [comment]
> 您好，请问LR和HR数据是怎么存放的，同时还修改了哪些地方么？

# Data specifications
parser.add_argument('--dir_data', type=str, default='E:/Dataset/DASR',
修改了训练集存放的地址，DASR中放有DF2K。
DF2K 包含 HR 和LR_bicubic

**Comment by raychl94** [comment]
> > 您好，请问LR和HR数据是怎么存放的，同时还修改了哪些地方么？
> 
> # Data specifications
> parser.add_argument('--dir_data', type=str, default='E:/Dataset/DASR', 修改了训练集存放的地址，DASR中放有DF2K。 DF2K 包含 HR 和LR_bicubic
